---
- name: Delete Folder
  hosts: group_02
  vars:
    folder: ~/nestjs-002-smartranking-microservices
  tasks:
    - name: Executar rm -rf
      become: true
      shell: >
        rm -rf {{folder}}
