version: '3.3'
services:
    rabbitmq3:
        container_name: 'rabbitmq'
        image: rabbitmq:3.8-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=fabiocaettano
            - RABBITMQ_DEFAULT_PASS=A1B2C3
        ports:
            - "5672:5672"
            - "15672:15672"   